## 06 ``numpy.array`` 合并和分割

In [1]:
import numpy as np

### ``numpy.array`` 的合并

In [2]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [3]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [4]:
z = np.array([666, 666, 666])
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [5]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [6]:
np.concatenate([A, A], axis=1) # 默认axis是0，代表第一个维度的方向拼接，设置为1代表第二个维度的方向，列的方向

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [7]:
np.concatenate([A, z]) #concatenate只能处理维数一样的情况

ValueError: all the input arrays must have same number of dimensions

In [9]:
np.concatenate([A, z.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [10]:
np.vstack([A, z]) #再垂直方向叠加

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [11]:
B = np.full((2,2), 100)

In [12]:
np.hstack([A, B]) #再水平方向叠加

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [13]:
np.hstack([A, z])

ValueError: all the input arrays must have same number of dimensions

### ``numpy.array`` 的分割

In [14]:
x = np.arange(10)
x    

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x1, x2, x3 = np.split(x, [3, 7]) #指定了2个分割点，一个是3，一个是7

In [16]:
x1

array([0, 1, 2])

In [17]:
x2

array([3, 4, 5, 6])

In [18]:
x3

array([7, 8, 9])

In [19]:
x1, x2 = np.split(x, [5])

In [20]:
x1

array([0, 1, 2, 3, 4])

In [21]:
x2

array([5, 6, 7, 8, 9])

In [22]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
A1, A2 = np.split(A, [2]) #默认情况下是基于行所在的维度切割，

In [36]:
A1  #因此我这里是前2行

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [37]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
A1, A2 = np.split(A, [2], axis=1) #再列的维度进行切分

In [39]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [40]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [25]:
upper, lower = np.vsplit(A, [2]) #再垂直方向切割

In [26]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [27]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
left, right = np.hsplit(A, [2])

In [29]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [30]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [31]:
data = np.arange(16).reshape((4, 4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
X, y = np.hsplit(data, [-1])

In [33]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [34]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [35]:
y[:, 0]

array([ 3,  7, 11, 15])