## 09 ``Numpy`` 中arg运算

In [1]:
import numpy as np

In [2]:
x = np.random.normal(0, 1, 1000000)

### 索引

In [3]:
np.argmin(x) #返回的是索引值

924142

In [4]:
x[886266]

0.5357058332863539

In [5]:
np.min(x)

-5.146339641727085

In [6]:
np.argmax(x)

679504

In [7]:
x[4851]

-1.1886200598920158

In [8]:
np.max(x)

4.90903783276991

### 排序和使用索引

In [9]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [10]:
np.random.shuffle(x)
x

array([ 2,  1,  7,  3,  4, 13,  0, 15,  8,  9, 11, 10, 12,  5, 14,  6])

In [11]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
x

array([ 2,  1,  7,  3,  4, 13,  0, 15,  8,  9, 11, 10, 12,  5, 14,  6])

In [13]:
x.sort()

In [14]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
X = np.random.randint(10, size=(4,4))
X

array([[8, 2, 2, 1],
       [4, 8, 3, 7],
       [0, 6, 8, 1],
       [0, 8, 7, 4]])

In [27]:
np.sort(X, axis=0)

array([[0, 2, 2, 1],
       [0, 6, 3, 1],
       [4, 8, 7, 4],
       [8, 8, 8, 7]])

In [28]:
np.sort(X, axis=1)

array([[1, 2, 2, 8],
       [3, 4, 7, 8],
       [0, 1, 6, 8],
       [0, 4, 7, 8]])

#### 使用索引

In [18]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
np.random.shuffle(x)

In [20]:
x

array([ 7, 12, 14,  8, 13, 10,  5,  0, 15,  9,  6,  2, 11,  4,  3,  1])

In [21]:
np.argsort(x)

array([ 7, 15, 11, 14, 13,  6, 10,  0,  3,  9,  5, 12,  1,  4,  2,  8],
      dtype=int64)

In [22]:
np.partition(x, 3)

array([ 0,  1,  2,  3,  4, 10,  5,  7,  8,  9,  6, 13, 11, 12, 14, 15])

In [23]:
np.argpartition(x, 3)

array([ 7, 15, 11, 14, 13,  5,  6,  0,  3,  9, 10,  4, 12,  1,  2,  8],
      dtype=int64)

In [24]:
X

array([[8, 2, 2, 1],
       [4, 8, 3, 7],
       [0, 6, 8, 1],
       [0, 8, 7, 4]])

In [25]:
np.argsort(X, axis=1)

array([[3, 1, 2, 0],
       [2, 0, 3, 1],
       [0, 3, 1, 2],
       [0, 3, 2, 1]], dtype=int64)

In [26]:
np.argpartition(X, 2, axis=1)

array([[3, 1, 2, 0],
       [2, 0, 3, 1],
       [0, 3, 1, 2],
       [0, 3, 2, 1]], dtype=int64)