## 03 测试我们的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets 

In [2]:
iris = datasets.load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [3]:
X = iris.data

In [4]:
y = iris.target

In [5]:
X.shape

(150, 4)

In [6]:
y.shape

(150,)

### train_test_split

分离出一部分数据做训练，另外一部分数据做测试。

In [7]:
y #通过打印可以知道，y是排好序的

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
shuffled_indexes = np.random.permutation(len(X))
shuffled_indexes

array([143,   9,  77,  68, 121,  93,  56,  99, 110, 112,  25,  29,  36,
        19, 107, 129,  60, 120,   4, 122,  62,  92, 128, 126,  78, 127,
       124,   7,   1,  66,  38,  80,  72, 119, 140, 101, 118, 149, 111,
        31,  71,  46,  82, 115, 147,  94,  34,  83, 106,  90, 136,  85,
        44,  16, 109, 141, 131,  88,  97,  81, 138, 134, 139, 117, 142,
        30, 114, 132,  91,  73,  28,  41,  45, 135,  61, 133,  12,  11,
        53, 145,  18,  58, 146,  39, 130,  33,  64,  86, 123, 137, 125,
        95, 103,  54,  96,  74,  52,  79,  15, 148,  17,  50,  67,   6,
        37,  40,  24,   8,  76,  47, 116,  14,  59,  35,  42,  20,  87,
        98, 104,  26,  22,   3, 144, 102,   5,  43,  69,  48,  70,   2,
       105,  23, 108,  51,  49,  55,  65,  10,  57,  13,  21, 100,  89,
        27,  32,  63, 113,  84,  75,   0])

In [9]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [10]:
test_indexes = shuffled_indexes[:test_size]
train_indexes = shuffled_indexes[test_size:]

In [11]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [12]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [13]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 封装

In [14]:
from playML.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [15]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [16]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 测试我们的算法

In [17]:
from playML.kNN import KNNClassifier

my_knn_clf = KNNClassifier(k=3)
my_knn_clf.fit(X_train, y_train)
y_predict = my_knn_clf.predict(X_test)

In [18]:
y_predict

array([0, 1, 2, 1, 0, 2, 1, 0, 1, 0, 0, 2, 1, 1, 2, 2, 0, 1, 1, 0, 0, 0,
       1, 2, 1, 2, 0, 2, 0, 1])

In [19]:
y_test

array([0, 1, 2, 1, 0, 2, 1, 0, 1, 0, 0, 2, 1, 1, 2, 2, 0, 1, 1, 0, 0, 0,
       1, 2, 1, 2, 0, 1, 0, 1])

In [20]:
sum(y_predict == y_test)

29

In [21]:
sum(y_predict == y_test) / len(y_test)

0.9666666666666667

#### sklearn中的train_test_split

In [22]:
from sklearn.model_selection import train_test_split

train_test_split

<function sklearn.model_selection._split.train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)>

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [24]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [25]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
